import { Inter } from "next/font/google";
import '../scss/volt.scss';
import { MyProvider } from "@/helpers/changeShoppingCart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bookstore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MyProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </MyProvider>
  );
}
